### ISSUE TITLE
What will happening if I use the 5V/16Mhz pro mini

### ISSUE THREAD

**Issue by jindaxia** [TheDIYGuy999/RC_Transmitter#5]
I only have 5v/16mhz pro mini ， how if i can use this board？

**Comment by TheDIYGuy999** [comment]
You can use it, but make sure the NRF24 radio module is supplied by 3.3V. Also make sure, that your minimum battery voltage is about 5.7V

**Comment by jindaxia** [comment]
Thanks，

**Comment by jindaxia** [comment]
finally，  I replaced the MIC2505 with the 3.3v version on the board
