### ISSUE TITLE
Connection/pairing problem

### ISSUE THREAD

**Issue by Kiriki-kun** [TheDIYGuy999/RC_Transmitter#6]
Hi,

I assembled transmitter and receiver.
Transmitter is working, i can operate menu.
I can't verify if receiver is working, because there is no indication of work.
Receiver should be set to ID 1.
I checked the radio voltage and all connections. They are good.

When i power up the receiver and transmitter, they won't connect.
Is there another step to pair them? 
Do you have any suggestion what to check?
After few hours I'm out of ideas.

Thanks for help
Kiriki

**Comment by TheDIYGuy999** [comment]
Hi, really hard to tell. The code is uploading without issues? If you have a 2nd transmitter, you can also use it as a receiver with graphical feedback, according to the manual.

Are you sure your receiver is programmed with ID 1? Maybe, one of your NRF24 radio modules is defective?

**Comment by Kiriki-kun** [comment]
Thank you for your answer.
I have problem with verificatio after writing, but writing is working good. I flashed different configuration to transmitter, and i could see the difference after turning it on.
I dont have second transmitter, i will order parts if everything else fail (i used all my spare sparts just to make one run :)).
I will try to write simple code just to test if radio modules are working.

So i assume, that transmitter and receiver should pair after couple of seconds, without additional steps? Just turn both on, and wait?

**Comment by Kiriki-kun** [comment]
Can it be because i have 16 Mhz arduino in transmitter, and 8 Mhz in receiver?

**Comment by TheDIYGuy999** [comment]
No, it does not matter (if your boot loader is the right one for the frequency), but what is your transmitter battery voltage? Is it high enough for stable 5V VCC? And yes, they should pair immediately, if they are on the same channel. You could try to add a 100nF ceramic capacitor across the NFRF module 3.3V & GND pins, it makes the receiver radio much more stable, at least in my case. All the solder joints are looking god with a magnifier? Maybe you can post pictures?

**Comment by johnlenfr** [comment]
@Kiriki-kun : seams like you have a problem with initialization of NRF24.

Test your NRF24 with simple code before testing the transmiter code of @TheDIYGuy999 

See https://forum.arduino.cc/index.php?topic=421081.0

Don't forget to wait 3 to 4 secs for NRF24 init.

Could also be a problem of library you are using.

**Comment by Kiriki-kun** [comment]
![receiver_debug](https://user-images.githubusercontent.com/63404821/79621049-4679c000-8112-11ea-9917-98c18c00c28e.PNG)
![Transmitter_debug](https://user-images.githubusercontent.com/63404821/79621056-4aa5dd80-8112-11ea-9c2c-ca86accd5d3f.PNG)
Hi,
Right now, i managed to setup serial monitor and run debug code. I'm attaching printed debug.
I can see that all anthena parameters are empty, but i'm not sure if they are not filled after establishing the connection.
Can you look at it? This is how debug should look like for not connected transmitter or receiver?

**Comment by Kiriki-kun** [comment]
ok, i made it work.
Not really sure what wasn't working. I tried few test programs, resoldered radios, and now it's working :)
Thank you very much for yor help :)

**Comment by TheDIYGuy999** [comment]
Great. I knew you would solve the issue. Well done and have fun with it. I would love to see pictures of your work, if possible. And sorry, I forgot to answer your previous question.
