### ISSUE TITLE
Expected variable ranges

### ISSUE THREAD

**Issue by debonthj** [TheDIYGuy999/RC_Transmitter#8]
Great project! I am building this into a RC car style pistol grip transmitter, different brand though than the WLToys. What are the expected ranges of the wheel left/right and throttle fwd/rev that are being sent to the receiver? What I am getting right now:

Throttle: fwd = 72, mid = 50, rev = 37
Steer: left = 37, mid = 50, right =63.

Is this correct or should it be a range between 0-100?

I may not be understanding this correctly:

`// Joystick calibration
int range = 1023; // 1023, if entire pot wiper range is used
int reverseEndpoint = 0; // the point, where the throttle joystick hits its reverse end stop
`

**Comment by debonthj** [comment]
These are the raw values from the signal wires of the throttle and steering wheel pots via AnalogRead on A1 (steering) and A3 (throttle), pots powered by 5V and GND. 

A1 (steering) 

- 320 (left)
- 447 (neutral)
- 585 (right)

A3 (throttle)

- 682 (go)
- 460 (neutral)
- 332 (rev)

**Comment by TheDIYGuy999** [comment]
Thanks, play with:
 range (probably around 265)
reverseEndpoint (around 332, until it goes down to 0)
the range should be 0 - 100

**Comment by debonthj** [comment]
Thanks. Through trial and error I got a good range setting (640). This gives me the full range for steering, as well as the throttle reverse, but for throttle FWD it gets to 100 at around 2/3 of the trigger position. reverseEndpoint does not seem to have an impact. I suppose a separate range is needed for steering and throttle given the differences in their resistances as per above. Not a huge issue but something I may code in in the future if this project gets alot of use. FYI the transmitter is this: https://www.carson-modelsport.com/en/products/carson-modelsport/accessories/radio-controls/reflex-wheel-start-24g-radio-white-500500103/

Thanks again!

**Comment by TheDIYGuy999** [comment]
Thanks for the feedback. Yes, a separate range might be useful, but for my transmitters it was not required so far.
